name: Build Image On Release

on:
  workflow_call:
    inputs:
      repo_owner:
        required: true
        type: string
      app_name:
        required: true
        type: string
      dockerhub_user:
        required: false
        type: string
    secrets:
      dockerhub_password:
        required: false

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.5
      -  
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: |
            ${{ inputs.repo_owner }}/${{ inputs.app_name }}
            ghcr.io/${{ inputs.repo_owner }}/${{ inputs.app_name }}
          labels: |
            org.opencontainers.image.title=${{ inputs.app_name }}
            org.opencontainers.image.description=${{ inputs.app_name }}
            org.opencontainers.image.vendor=${{ inputs.repo_owner }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Login to DockerHub
        if: ${{ inputs.dockerhub_user }}
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ inputs.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ inputs.repo_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v1.6.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          set: |
            image.args.BUILD_DATE=$(date '+%Y-%m-%dT%H:%M:%S%:z')
            image.args.VERSION=${{ github.event.release.tag_name }}            
          targets: image-all
          push: true
